clickhouse_macros:
  layer: 01
  shard: "shard_3"
  replica: "orange1"

clickhouse_server_id: 3

clickhouse_cl_keepers:
  - { host: "blue1.xtl", port: 9234 }
  - { host: "green1.xtl", port: 9234 }
  - { host: "orange1.xtl", port: 9234 }